version = 0.1
[default.deploy.parameters]
stack_name = "gptcotts-fastapi"
resolve_s3 = true
s3_prefix = "gptcotts-fastapi"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["FastAPIFunction=816149945621.dkr.ecr.eu-north-1.amazonaws.com/gptcottsfastapi3425c386/fastapifunctionead79d0drepo"]
