repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
    - id: ruff
      args: ['--fix', 'backend/']
    - id: ruff-format
- repo: https://github.com/qoomon/git-conventional-commits
  rev: v2.7.2
  hooks:
    - id: conventional-commits
