exclude = [
  ".git",
  "venv",
  "gpt-cotts-frontend"
]

line-length = 88
indent-width = 4

[lint]
select = ["E4", "E7", "E9", "F", "W", "I", "N", "D"]
ignore = ["D104"]

fixable = ["ALL"]
unfixable = []

[lint.pydocstyle]

convention = "google"

[line.per-file-ignores]
"__init__.py" = ["F401", "E402", "D"]
"test_*.py" = ["D"]

[format]
quote-style = "double"

