refresh:
	python3 data_processing/refresh.py --weaviate localhost

run:
	flask --app frontend/app.py run --host 0.0.0.0

run-debug:
	flask --app frontend/app.py run --debugger --reload

reqs:
	pip freeze > requirements.txt
