name: ruff-check
on: [pull_request]
jobs:
  Run-Ruff-Check:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: run ruff check
        run: ruff check .
