name: ruff
on: [pull_request]
jobs:
  Run-Ruff-Check:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: install reqs
        run: pip install -r requirements_dev.txt
      - name: run ruff check
        run: ruff check .
