name: ruff
on: [pull_request]
jobs:
  Run-Ruff-Check:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: install reqs
        run: pip install ruff==0.6.1
      - name: run ruff check
        run: ruff check .
      - name: run ruff format
        run: ruff format
